CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CPFCNPJ VARCHAR(14) NOT NULL UNIQUE,
    ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE CONTA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_ABERTURA DATE NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);


CREATE TABLE CLIENTE_CONTA (
    CLIENTE_ID INT NOT NULL,
    CONTA_ID INT NOT NULL,
    PRIMARY KEY (CLIENTE_ID, CONTA_ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    FOREIGN KEY (CONTA_ID) REFERENCES CONTA(ID)
);


CREATE TABLE CARTAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(20) NOT NULL UNIQUE,
    VALIDADE VARCHAR(8) NOT NULL,
    TIPO ENUM('FISICO', 'VIRTUAL') NOT NULL,
    CONTA_ID INT NOT NULL,
    VALIDADO BOOLEAN DEFAULT FALSE,
    CVV VARCHAR(3) NOT NULL,
    CARTAO_FISICO_ID INT DEFAULT NULL,
    FOREIGN KEY (CONTA_ID) REFERENCES CONTA(ID),
    FOREIGN KEY (CARTAO_FISICO_ID) REFERENCES CARTAO(ID),
    ATIVO BOOLEAN DEFAULT TRUE,
    CHECK (
        (TIPO = 'FISICO' AND CARTAO_FISICO_ID IS NULL) OR
        (TIPO = 'VIRTUAL' AND CARTAO_FISICO_ID IS NOT NULL)
    )
);

COMMIT;